sudo: required
dist: xenial
language: cpp

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
    - libasound2-dev
    - libfftw3-dev
    - libhunspell-dev
    - libfribidi-dev
    - libass-dev
    - libicu-dev
    - luarocks
    - cmake
    - build-essential
    - libboost-all-dev
    - libffms2-dev
    - libfontconfig1-dev
    - libopenal-dev
    - libuchardet-dev
    - libwxgtk3.0-dev

install:
  - sudo luarocks install busted > /dev/null
  - sudo luarocks install moonscript > /dev/null
  - sudo luarocks install uuid > /dev/null

script:
  # Remove the CMake provided by travis
  - sudo rm -rf /usr/local/cmake*

  - ./build/version.sh .
  - mkdir build-dir
  - cd build-dir
  - cmake -DCMAKE_CXX_FLAGS='-std=gnu++11' ..
  - make -j2

notifications:
  email:
  - on_success: change
  - on_failure: change

